# Generated by Django 4.2 on 2023-04-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('purchase_bonus', models.TextField(blank=True, default='')),
                ('bonus_expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('income', 'Income'), ('expenses', 'Expenses'), ('investments', 'Investments'), ('transfers', 'Transfers')], max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='users.myuser')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='users.myuser')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
