# Generated by Django 4.2 on 2023-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'permissions': [('view_own_transactions', 'Can view own transactions'), ('view_all_transactions', 'Can view all transactions')]},
        ),
    ]
