# Generated by Django 4.2 on 2023-04-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_hide_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('debit/credit card', 'Debit/Credit Card'), ('blockchain wallet transfer', 'Blockchain Wallet Transfer'), ('paypal', 'Paypal')], max_length=50),
        ),
    ]
