# Generated by Django 4.1.9 on 2023-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('treatment_provided', models.TextField()),
                ('medical_history_notes', models.TextField(blank=True, null=True)),
                ('total_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=15)),
                ('reference_number', models.CharField(max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
